image: dvcorg/cml:0-dvc2-base1

pipelines:
  default:
    - step:
        script:
          - npm install -g https://github.com/iterative/cml#cml-send-comment-pr-rev-parse
          
          - sudo apt update && sudo apt install awscli
          - pip install -r requirements.txt
          
          - TB_URL="NOT READY"

          - echo "# CML report" > report.md
          - echo $TB_URL >> report.md
          - cml-send-comment report.md

          - python train.py
          
          - echo "# CML report" > report.md
          - echo $TB_URL >> report.md
          - cat output/metrics.txt >> report.md
          - cml-publish output/confusion_matrix.png --md >> report.md
          - cml-pr --md output/* >> report.md
          - cml-send-comment --update report.md
          - cml-send-comment --update --pr --commit-sha HEAD report.md
