name: train-my-model

on: [push]

env:
  REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  # deploy-runner:
  #   runs-on: [ubuntu-latest]
  #   steps:
  #     - uses: actions/checkout@v2

  #     - uses: iterative/setup-cml@v1

  #     - name: deploy
  #       shell: bash
  #       run: |
  #         cml-runner \
  #         --reuse \
  #         --cloud-spot \
  #         --cloud aws \
  #         --cloud-region us-west \
  #         --cloud-type=g3.4xlarge \
  #         --cloud-hdd-size 64 \
  #         --labels=gpu

  run:
    #needs: deploy-runner
    runs-on: [ubuntu-latest]
    # runs-on: [self-hosted,gpu]
    # container: 
    #   image: docker://dvcorg/cml:0-dvc2-base1-gpu
    #   options: --gpus all

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
      env:
        token: ${{ secrets.REPO_TOKEN }}

    - name: deps
      run: |
        sudo apt update
        sudo apt install -y libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev librsvg2-dev awscli

    - uses: iterative/setup-cml@v1

    - uses: iterative/setup-dvc@v1
      # with:
      #   version: '2.7.3'

    - uses: actions/setup-python@v2
      with:
        python-version: '3.6'

    - name: cml
      env:
        REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
        AWS_EC2_METADATA_DISABLED: true
        #DVC_EXP_AUTO_PUSH: true
        #DVC_EXP_GIT_REMOTE: origin
        DVC_EXP_GIT_REMOTE: https://DavidGOrtega:${{secrets.REPO_TOKEN}}@github.com/DavidGOrtega/fashion_mnist.git
        DVC_EXP_AUTO_PUSH: true
      shell: bash
      run: |
        pip install -r requirements.txt
        
        # git fetch --prune

        #needed by dvc exp apply
        # git config --global user.email "g.ortega.david@gmail.com"
        # git config --global user.name "DavidGOrtega"

        EXP_NAME=${GITHUB_REPOSITORY}-cml-run-${GITHUB_SHA}
        # || because generates an error
        EXP_AVAIL=$(dvc exp pull --run-cache origin $EXP_NAME || echo '')
        if [[ -z "$EXP_AVAIL" ]]; then
            echo "############\nFirst Time\n############"
            dvc exp run -n $EXP_NAME --pull -v
        else    
            echo "############\nResuming\n############"
            dvc exp apply $EXP_NAME
            dvc exp run -v
        fi

        echo "# CML report" > report.md
        (cml-publish model/confusion_matrix.png --md >> report.md) || echo 'model/confusion_matrix.png'
        cml-send-comment report.md 
        cml-pr dvc.lock

    # - name: Setup tmate session
    #   if: ${{ failure() }}
    #   uses: mxschmitt/action-tmate@v3
    #   env:
    #     REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     AWS_DEFAULT_REGION: us-east-1
    #     AWS_EC2_METADATA_DISABLED: true
    #     DVC_EXP_GIT_REMOTE: https://DavidGOrtega:${{secrets.REPO_TOKEN}}@github.com/DavidGOrtega/fashion_mnist.git
    #     DVC_EXP_AUTO_PUSH: true
