name: train-my-model

on: [push]

jobs:
  run:
    runs-on: [self-hosted,cml-env]
    steps:
    - uses: actions/checkout@v2
    - uses: iterative/setup-cml@v1
    - uses: iterative/setup-dvc@v1
    - uses: actions/setup-python@v2
      with:
        python-version: '3.6'

    - name: cml
      env:
        REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
      shell: bash
      run: |
        python --version
        dvc --version

        pip install -r requirements.txt
      
        echo "# CML report" > report.md
        cml-send-comment report.md 
 