on: workflow_dispatch
jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: |
        export TF_VAR_done="$(uuidgen)"
        
        terraform init
        terraform apply --auto-approve
        terraform refresh && terraform show
        
        while sleep 10; do
          terraform refresh && terraform show --json |
            grep --fixed-strings "$TF_VAR_done" && break
        done
        
        terraform destroy --auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        
        TF_VAR_name: helio-${{ github.run_id }}
        TF_VAR_repo_token: ${{ secrets.REPO_TOKEN }}
        
