name: train-my-model

on: [push]

jobs:
  deploy-runner:
    env:
      REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      GOOGLE_APPLICATION_CREDENTIALS_DATA: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_DATA }}

    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1

      - name: deploy
        shell: bash
        run: |
          cml-runner \
          --cloud-spot \
          --cloud aws \
          --cloud-type t2.medium \
          --labels cml4

  run:
    timeout-minutes: 5000
    runs-on: [self-hosted,cml4]
    needs: deploy-runner
    container: 
      image: docker://dvcorg/cml:0-dvc2-base1

    steps:
    - uses: actions/checkout@v2

    - name: cml
      env:
        REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
        AWS_EC2_METADATA_DISABLED: true
        TB_CREDENTIALS: ${{ secrets.TB_CREDENTIALS }}
      run: |
        sudo apt update && sudo apt install awscli
        
        pip install -r requirements.txt
        
        TB_URL="NOT READY"

        echo "# CML report" > report.md
        echo $TB_URL >> report.md
        cml-send-comment --update report.md

        python train.py
        
        echo "# CML report" > report.md
        cml-pr --md output/* >> report.md
        echo $TB_URL >> report.md
        cat output/metrics.txt >> report.md
        cml-publish output/confusion_matrix.png --md >> report.md
        cml-send-comment --update report.md
