name: train-my-model

on: [push]

env:
  REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  # deploy-runner:
  #   runs-on: [ubuntu-latest]
  #   steps:
  #     - uses: actions/checkout@v2

  #     - uses: iterative/setup-cml@v1

  #     - name: deploy
  #       shell: bash
  #       run: |
  #         cml-runner \
  #         --reuse \
  #         --cloud-spot \
  #         --cloud aws \
  #         --cloud-region us-west \
  #         --cloud-type=g3.4xlarge \
  #         --cloud-hdd-size 64 \
  #         --labels=gpu

  run:
    #needs: deploy-runner
    runs-on: [ubuntu-latest]
    # runs-on: [self-hosted,gpu]
    # container: 
    #   image: docker://dvcorg/cml:0-dvc2-base1-gpu
    #   options: --gpus all

    steps:
    - uses: actions/checkout@v2
      env:
        token: ${{ secrets.REPO_TOKEN }}

    - name: deps
      run: |
        sudo apt update
        sudo apt install -y libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev librsvg2-dev awscli

    - uses: iterative/setup-cml@v1

    - uses: iterative/setup-dvc@v1

    - uses: actions/setup-python@v2
      with:
        python-version: '3.6'

    - name: cml
      env:
        REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
        AWS_EC2_METADATA_DISABLED: true
        #DVC_EXP_AUTO_PUSH: true
        #DVC_EXP_GIT_REMOTE: origin
        DVC_EXP_GIT_REMOTE: https://DavidGOrtega:${{secrets.REPO_TOKEN}}@github.com/DavidGOrtega/fashion_mnist.git
        DVC_EXP_AUTO_PUSH: true
      run: |
        pip install -r requirements.txt

        # python train.py

        # git config --global user.email "g.ortega.david@gmail.com"
        # git config --global user.name "DavidGOrtega"
        # git remote rm origin
        # git remote add origin ""
        # dvc pull --run-cache || echo 'Forgive this :pray:'
        # dvc exp run --pull -v
        # dvc push --run-cache

        git fetch --prune
        dvc pull || echo 'Forgive this :pray:'
        dvc exp run -v

        echo "# CML report" > report.md
        cml-publish model/confusion_matrix.png --md >> report.md
        cml-send-comment report.md 
        cml-pr dvc.lock
