name: train-my-model

on: [push]

jobs:
  # deploy-runner:
  #   env:
  #     REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
  #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  #   runs-on: [ubuntu-latest]
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: iterative/setup-cml@v1

  #     - name: deploy
  #       shell: bash
  #       run: |
  #         cml-runner \
  #         --cloud-spot \
  #         --cloud aws \
  #         --cloud-region us-west \
  #         --cloud-type t2.medium \
  #         --labels test2

  run:
    timeout-minutes: 5000
    runs-on: [self-hosted,gpu]
    #needs: deploy-runner
    #container: 
      #image: docker://dvcorg/cml:0-dvc2-base1

    steps:
    - uses: actions/checkout@v2

    - name: cml
      env:
        REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
        AWS_EC2_METADATA_DISABLED: true
        TB_CREDENTIALS: ${{ secrets.TB_CREDENTIALS }}
      run: |
        echo 'nice'
        
