name: train-tpi

on: [push]

  train:
    timeout-minutes: 5000
    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - name: tpi
      env:
        REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        cat <<EOF > main.tf
        terraform {
          required_providers {
            xpd = {
              source = "0x2b3bfa0/xpd",
            }
          }
        }

        provider "xpd" {}
        variable "name" {}

        resource "xpd_task" "task" {
          cloud = "aws"
          name  = var.name

          directory = "${path.root}"

          script = <<-END
            #!/bin/bash
            npm install -g --unsafe https://github.com/iterative/cml#cml-send-comment-pr-rev-parse

            sudo apt update && sudo apt install awscli
            pip install -r requirements.txt

            python train.py
            
            echo "# CML report" > report.md
            echo $TB_URL >> report.md
            cat output/metrics.txt >> report.md
            cml-publish output/confusion_matrix.png --md >> report.md
            cml-pr --md output/* >> report.md
            cml-send-comment --update report.md
            cml-send-comment --update --pr --commit-sha HEAD report.md
          END
        }
        EOF

        NAME=$GITHUB_REPOSITORY-$GITHUB_RUN_ID
        terraform init 
        terraform apply --auto-approve -var 'name=$NAME'
