name: train-tpi

on: [push]

jobs:
  train-tpi:
    timeout-minutes: 5000
    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - name: tpi
      env:
        REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        cat <<EOF > main.tf
        terraform {
          required_providers {
            xpd = {
              source = "0x2b3bfa0/xpd",
            }
          }
        }

        provider "xpd" {}
        variable "name" {}
        
        EOF

        NAME=$GITHUB_REPOSITORY-$GITHUB_RUN_ID
        terraform init 
        terraform apply --auto-approve -var 'name=$NAME'
